export { default as About } from "./about";
export { default as Author } from "./author";
export { default as ErrorPage } from "./errorPage";
export { default as HomePage } from "./homePage";
export { default as TaskPage } from "./task";
export { default as Presentation } from "./presentation";
// export { default as Laboratory } from "./laboratory";
export { default as Task } from "./task";
export { default as Method } from "./methodics";
export { default as Tests } from "./tests";
